language: python
python:
- "2.7.13"
sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec', '<3.0.0'
    #Version was frozen, because of issues in the version of inspec >3.0.0 -- see https://mirantis.jira.com/browse/PROD-24324 for more info
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git', :branch => 'master'
  - bundle install

env:
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=client-compose
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=client-container
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2016.3 SUITE=host-single
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=client-compose
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=client-container
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2017.7 SUITE=host-single
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=client-compose
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=client-container
  - PLATFORM=epcim/salt:saltstack-ubuntu-xenial-salt-2018.3 SUITE=host-single
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=client-compose
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=client-container
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2017.7 SUITE=host-single
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=client-compose
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=client-container
#  - PLATFORM=epcim/salt:saltstack-ubuntu-bionic-salt-2018.3 SUITE=host-single

before_script:
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false