agent:
  input:
    procstat:
      process:
        dockerd:
          exe: dockerd
    docker:
      endpoint: unix:///var/run/docker.sock
      timeout: 5
      perdevice: true
      total: false
      gather_services: true
